export type SupportedLanguage = { code: string; native: string; english: string }

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'af', native: 'Afrikaans', english: 'Afrikaans' },
  { code: 'am', native: 'አማርኛ', english: 'Amharic' },
  { code: 'sq', native: 'Shqip', english: 'Albanian' },
  { code: 'hy', native: 'Հայերեն', english: 'Armenian' },
  { code: 'az', native: 'Azərbaycan', english: 'Azerbaijani' },
  { code: 'eu', native: 'Euskara', english: 'Basque' },
  { code: 'bn', native: 'বাংলা', english: 'Bengali' },
  { code: 'bs', native: 'Bosanski', english: 'Bosnian' },
  { code: 'bg', native: 'Български', english: 'Bulgarian' },
  { code: 'my', native: 'မြန်မာဘာသာ', english: 'Burmese' },
  { code: 'ca', native: 'Català', english: 'Catalan' },
  { code: 'zh', native: '中文 (简体)', english: 'Chinese Simplified' },
  { code: 'zh-TW', native: '中文 (繁體)', english: 'Chinese Traditional' },
  { code: 'hr', native: 'Hrvatski', english: 'Croatian' },
  { code: 'cs', native: 'Čeština', english: 'Czech' },
  { code: 'da', native: 'Dansk', english: 'Danish' },
  { code: 'nl', native: 'Nederlands', english: 'Dutch' },
  { code: 'en', native: 'English', english: 'English' },
  { code: 'et', native: 'Eesti', english: 'Estonian' },
  { code: 'fil', native: 'Filipino', english: 'Filipino' },
  { code: 'fi', native: 'Suomi', english: 'Finnish' },
  { code: 'fr', native: 'Français', english: 'French' },
  { code: 'gl', native: 'Galego', english: 'Galician' },
  { code: 'ka', native: 'ქართული', english: 'Georgian' },
  { code: 'de', native: 'Deutsch', english: 'German' },
  { code: 'el', native: 'Ελληνικά', english: 'Greek' },
  { code: 'gu', native: 'ગુજરાતી', english: 'Gujarati' },
  { code: 'ha', native: 'Hausa', english: 'Hausa' },
  { code: 'hi', native: 'हिन्दी', english: 'Hindi' },
  { code: 'hu', native: 'Magyar', english: 'Hungarian' },
  { code: 'is', native: 'Íslenska', english: 'Icelandic' },
  { code: 'ig', native: 'Igbo', english: 'Igbo' },
  { code: 'id', native: 'Bahasa Indonesia', english: 'Indonesian' },
  { code: 'ga', native: 'Gaeilge', english: 'Irish' },
  { code: 'it', native: 'Italiano', english: 'Italian' },
  { code: 'ja', native: '日本語', english: 'Japanese' },
  { code: 'kn', native: 'ಕನ್ನಡ', english: 'Kannada' },
  { code: 'kk', native: 'Қазақша', english: 'Kazakh' },
  { code: 'km', native: 'ភាសាខ្មែរ', english: 'Khmer' },
  { code: 'ko', native: '한국어', english: 'Korean' },
  { code: 'lo', native: 'ພາສາລາວ', english: 'Lao' },
  { code: 'lv', native: 'Latviešu', english: 'Latvian' },
  { code: 'lt', native: 'Lietuvių', english: 'Lithuanian' },
  { code: 'mk', native: 'Македонски', english: 'Macedonian' },
  { code: 'mg', native: 'Malagasy', english: 'Malagasy' },
  { code: 'ms', native: 'Bahasa Melayu', english: 'Malay' },
  { code: 'ml', native: 'മലയാളം', english: 'Malayalam' },
  { code: 'mr', native: 'मराठी', english: 'Marathi' },
  { code: 'mn', native: 'Монгол', english: 'Mongolian' },
  { code: 'ne', native: 'नेपाली', english: 'Nepali' },
  { code: 'no', native: 'Norsk', english: 'Norwegian' },
  { code: 'pa', native: 'ਪੰਜਾਬੀ', english: 'Punjabi' },
  { code: 'pl', native: 'Polski', english: 'Polish' },
  { code: 'pt', native: 'Português', english: 'Portuguese' },
  { code: 'ro', native: 'Română', english: 'Romanian' },
  { code: 'ru', native: 'Русский', english: 'Russian' },
  { code: 'sr', native: 'Srpski', english: 'Serbian' },
  { code: 'si', native: 'සිංහල', english: 'Sinhala' },
  { code: 'sk', native: 'Slovenčina', english: 'Slovak' },
  { code: 'sl', native: 'Slovenščina', english: 'Slovenian' },
  { code: 'so', native: 'Soomaali', english: 'Somali' },
  { code: 'es', native: 'Español', english: 'Spanish' },
  { code: 'sw', native: 'Kiswahili', english: 'Swahili' },
  { code: 'sv', native: 'Svenska', english: 'Swedish' },
  { code: 'ta', native: 'தமிழ்', english: 'Tamil' },
  { code: 'te', native: 'తెలుగు', english: 'Telugu' },
  { code: 'th', native: 'ภาษาไทย', english: 'Thai' },
  { code: 'tr', native: 'Türkçe', english: 'Turkish' },
  { code: 'uk', native: 'Українська', english: 'Ukrainian' },
  { code: 'uz', native: "O'zbek", english: 'Uzbek' },
  { code: 'vi', native: 'Tiếng Việt', english: 'Vietnamese' },
  { code: 'cy', native: 'Cymraeg', english: 'Welsh' },
  { code: 'yo', native: 'Yorùbá', english: 'Yoruba' },
  { code: 'zu', native: 'isiZulu', english: 'Zulu' },
].sort((a, b) => a.english.localeCompare(b.english))

export function getLangLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.native : code
}
